// Crop catalog used for Plantix-style crop circles and community filters.
// emoji acts as the crop "photo"; bg is the circle tint.
export const CROP_CATALOG = [
    { id: 'almond', name: 'Almond', emoji: '🌰', bg: '#f5ede3' },
    { id: 'apple', name: 'Apple', emoji: '🍎', bg: '#fdecea' },
    { id: 'banana', name: 'Banana', emoji: '🍌', bg: '#fdf6dd' },
    { id: 'barley', name: 'Barley', emoji: '🌾', bg: '#f7f1df' },
    { id: 'bean', name: 'Bean', emoji: '🫘', bg: '#eef5e9' },
    { id: 'black_gram', name: 'Black & Green Gram', emoji: '🫛', bg: '#eaf3ea' },
    { id: 'brinjal', name: 'Brinjal', emoji: '🍆', bg: '#f3ecf8' },
    { id: 'cabbage', name: 'Cabbage', emoji: '🥬', bg: '#ebf6e9' },
    { id: 'cassava', name: 'Cassava', emoji: '🍠', bg: '#f6ede6' },
    { id: 'cauliflower', name: 'Cauliflower', emoji: '🥦', bg: '#eef5ea' },
    { id: 'chilli', name: 'Chilli & Capsicum', emoji: '🌶️', bg: '#fdecea' },
    { id: 'coconut', name: 'Coconut', emoji: '🥥', bg: '#f5efe8' },
    { id: 'coffee', name: 'Coffee', emoji: '☕', bg: '#f3ece6' },
    { id: 'cotton', name: 'Cotton', emoji: '☁️', bg: '#f0f4f8' },
    { id: 'cucumber', name: 'Cucumber', emoji: '🥒', bg: '#ecf6ea' },
    { id: 'grape', name: 'Grape', emoji: '🍇', bg: '#f2ecf8' },
    { id: 'maize', name: 'Maize', emoji: '🌽', bg: '#fdf6dd' },
    { id: 'mango', name: 'Mango', emoji: '🥭', bg: '#fdf1e0' },
    { id: 'onion', name: 'Onion', emoji: '🧅', bg: '#f9eee6' },
    { id: 'orange', name: 'Orange', emoji: '🍊', bg: '#fdf1e0' },
    { id: 'papaya', name: 'Papaya', emoji: '🍈', bg: '#f2f7e5' },
    { id: 'peanut', name: 'Peanut', emoji: '🥜', bg: '#f7f0e3' },
    { id: 'pomegranate', name: 'Pomegranate', emoji: '🍎', bg: '#fbe9ec' },
    { id: 'potato', name: 'Potato', emoji: '🥔', bg: '#f6f0e4' },
    { id: 'rice', name: 'Rice', emoji: '🌾', bg: '#f4f2e2' },
    { id: 'sugarcane', name: 'Sugarcane', emoji: '🎋', bg: '#e9f5ea' },
    { id: 'tomato', name: 'Tomato', emoji: '🍅', bg: '#fdecea' },
    { id: 'watermelon', name: 'Watermelon', emoji: '🍉', bg: '#eaf6ec' },
    { id: 'wheat', name: 'Wheat', emoji: '🌾', bg: '#f7f1df' },
];

export const cropByName = (name) =>
    CROP_CATALOG.find(c => c.name.toLowerCase() === (name || '').toLowerCase()) ||
    { id: 'other', name: name || 'Crop', emoji: '🌱', bg: '#eef5e9' };

// Growing guide per crop: temperature, rainfall, soil, pH, season, how-to
export const CROP_INFO = {
    almond: { temp: "15-30°C", rain: "500-750 mm", soil: "Deep, well-drained loamy soil", ph: "6.0-7.5", season: "Planted in winter (Dec-Jan); needs chilling hours", how: "Plant grafted saplings 6m apart. Needs cross-pollination — plant 2 varieties. Irrigate every 10 days in summer. Harvest when hulls split (Aug-Sep)." },
    apple: { temp: "21-24°C", rain: "1000-1250 mm", soil: "Loamy, rich in organic matter, well-drained", ph: "5.5-6.5", season: "Needs 1000-1500 chilling hours; hill regions", how: "Plant 1-year grafts in Jan-Feb at 3x3 m. Thin fruits to 1 per cluster. Harvest 130-135 days after bloom." },
    banana: { temp: "26-30°C", rain: "1700-2500 mm", soil: "Deep, rich loamy soil with good drainage", ph: "6.5-7.5", season: "Year-round in tropics; avoid frost", how: "Plant tissue-culture saplings 1.8x1.8 m. Apply 300g N, 100g P, 300g K per plant/year. Keep one sucker as follower. Bunch matures in 11-12 months." },
    barley: { temp: "12-25°C", rain: "400-500 mm", soil: "Sandy loam to loam, tolerates salinity", ph: "6.5-8.0", season: "Rabi (Oct-Nov sowing)", how: "Sow 100 kg seed/ha at 22 cm rows. 2-3 irrigations: crown root, flowering, grain fill. Harvest Mar-Apr." },
    bean: { temp: "16-30°C", rain: "400-500 mm", soil: "Well-drained sandy loam", ph: "6.0-7.0", season: "Kharif and Rabi; frost-sensitive", how: "Sow 25-30 kg/ha at 30x10 cm. Fixes own nitrogen — only starter dose needed. Support climbing types. Pick tender pods every 3-4 days." },
    black_gram: { temp: "25-35°C", rain: "600-800 mm", soil: "Loam to clay loam, moisture-retentive", ph: "6.5-7.8", season: "Kharif (Jun-Jul) and summer", how: "Sow 15-20 kg/ha at 30x10 cm. Treat seed with Rhizobium. Hoe at 25 days. Harvest when 80% pods blacken (70-90 days)." },
    brinjal: { temp: "22-30°C", rain: "600-1000 mm", soil: "Fertile sandy loam with organic matter", ph: "5.5-6.8", season: "Year-round; avoid severe cold", how: "Transplant 30-day seedlings at 60x60 cm. Apply FYM 25 t/ha. Use pheromone traps for shoot & fruit borer. Pick glossy fruits." },
    cabbage: { temp: "15-21°C", rain: "380-500 mm", soil: "Fertile loam rich in humus", ph: "6.0-6.8", season: "Winter (Sep-Nov transplant)", how: "Transplant 4-week seedlings at 45x45 cm. Keep moisture steady to stop head splitting. Top-dress N at 30 days. Harvest firm heads." },
    cassava: { temp: "25-32°C", rain: "1000-1500 mm", soil: "Sandy loam, deep and friable", ph: "5.5-6.5", season: "Start of rainy season", how: "Plant 20 cm stem cuttings at 90x90 cm. Weed for first 3 months. Avoid waterlogging. Harvest tubers at 8-11 months." },
    cauliflower: { temp: "15-20°C", rain: "400-500 mm", soil: "Rich loam with high organic matter", ph: "6.0-7.0", season: "Winter; variety timing critical", how: "Transplant 25-30 day seedlings at 45x45 cm. Apply borax 10 kg/ha to prevent hollow stem. Tie leaves to blanch curds. Harvest compact white curds." },
    chilli: { temp: "20-30°C", rain: "600-1250 mm", soil: "Well-drained loamy soil", ph: "6.0-7.0", season: "Kharif and summer", how: "Transplant 35-40 day seedlings at 60x45 cm. Mulch to hold moisture. Watch thrips & mites (leaf curl). Pick green or red-ripe for drying." },
    coconut: { temp: "27-32°C", rain: "1300-2300 mm", soil: "Coastal sandy or laterite, well-drained", ph: "5.2-8.0", season: "Plant May-Jun or Sep-Oct", how: "Plant 8 m apart in 1 m pits with FYM. Apply 500g N, 320g P, 1200g K/palm/year. Irrigate 100 L/palm/week in summer. Bears from year 6-8." },
    coffee: { temp: "15-28°C", rain: "1500-2500 mm", soil: "Deep friable loam rich in humus", ph: "6.0-6.5", season: "Plant with monsoon; needs shade", how: "Grow under 50% shade. Plant 2.5x2.5 m (Arabica). Blossom irrigation in March if rains fail. Pick only red-ripe cherries. Prune after harvest." },
    cotton: { temp: "21-30°C", rain: "500-1000 mm", soil: "Deep black cotton soil (regur)", ph: "6.0-8.0", season: "Kharif (Apr-May sowing)", how: "Sow with monsoon at 90x60 cm. Thin to 1 plant/hill. Monitor bollworm weekly with pheromone traps. Pick clean dry cotton in 3-4 rounds." },
    cucumber: { temp: "18-30°C", rain: "400-600 mm", soil: "Sandy loam rich in organic matter", ph: "6.0-7.0", season: "Summer and Kharif", how: "Sow 2-3 seeds/hill at 1.5x0.6 m. Trellis for straight fruits. Irrigate every 4-5 days. Pick tender fruits every 2 days." },
    grape: { temp: "15-35°C", rain: "500-800 mm (dry best)", soil: "Well-drained sandy loam", ph: "6.5-7.5", season: "Prune Oct (fruiting) & Apr (foundation)", how: "Train on pandal system at 3x3 m. Double pruning in India. Girdling + GA3 improves berry size. Harvest at 18-20 Brix sweetness." },
    maize: { temp: "21-30°C", rain: "500-800 mm", soil: "Deep fertile loam, well-drained", ph: "5.5-7.5", season: "Kharif, Rabi and spring", how: "Sow 20 kg/ha at 60x20 cm. N in 3 splits — critical at knee-high & tasseling. Never miss irrigation at silking. Harvest when husks dry." },
    mango: { temp: "24-30°C", rain: "750-2500 mm", soil: "Deep alluvial or laterite, well-drained", ph: "5.5-7.5", season: "Plant Jul-Aug; flowers Dec-Feb", how: "Plant grafts 10x10 m. No irrigation during flowering. Spray 2% KNO3 to induce flowering. Bag fruits against fruit fly. Harvest with stalk." },
    onion: { temp: "13-24°C", rain: "650-750 mm", soil: "Friable loam, non-crusting", ph: "6.0-7.5", season: "Rabi main; Kharif in some regions", how: "Transplant 45-day seedlings at 15x10 cm. Light frequent irrigation (shallow roots). Stop water when 50% tops fall. Cure 3-5 days before storing." },
    orange: { temp: "13-37°C", rain: "1000-1200 mm", soil: "Deep sandy loam, well-drained", ph: "5.5-7.5", season: "Plant Jun-Aug", how: "Plant budded plants 6x6 m. Bahar treatment: withhold water 30-40 days to set flowering. Foliar spray Zn & Fe. Harvest at colour break." },
    papaya: { temp: "22-32°C", rain: "1000-2000 mm", soil: "Rich sandy loam, perfect drainage", ph: "6.0-7.0", season: "Plant Jun-Sep or Feb-Mar; frost-free", how: "Plant 2-month seedlings at 1.8x1.8 m. Ring irrigation — water must not touch stem. Fruits from 9-10 months." },
    peanut: { temp: "25-32°C", rain: "500-1000 mm", soil: "Light sandy loam with calcium", ph: "6.0-7.0", season: "Kharif (Jun-Jul)", how: "Sow 100-120 kg pods/ha at 30x10 cm. Apply gypsum 250 kg/ha at flowering for pod fill. Earth up at pegging. Harvest when inner shell darkens." },
    pomegranate: { temp: "25-35°C", rain: "500-800 mm (semi-arid best)", soil: "Deep loamy, tolerates slight salinity", ph: "6.5-7.5", season: "Plant with monsoon", how: "Plant 5x3 m. Choose one bahar (flower season) and stress-induce it. Drip irrigation ideal. Bag fruits against borer. Harvest at yellowish-red rind." },
    potato: { temp: "15-25°C (tubers 17-19°C)", rain: "500-700 mm", soil: "Friable sandy loam rich in humus", ph: "5.2-6.4", season: "Rabi (Oct-Nov planting)", how: "Plant certified tubers 60x20 cm, 5 cm deep. Earth up at 25-30 days. Critical water at tuber initiation. Cut haulms 10 days before digging." },
    rice: { temp: "22-32°C", rain: "1000-2000 mm", soil: "Clay or clay loam that holds water", ph: "5.5-6.5", season: "Kharif main; Rabi where irrigated", how: "Transplant 25-30 day seedlings 20x15 cm. Keep 2-5 cm standing water. N in 3 splits. Drain 10 days before harvest at 80% golden grains." },
    sugarcane: { temp: "26-32°C", rain: "1100-1500 mm", soil: "Deep rich loam, well-drained", ph: "6.5-7.5", season: "Plant Jan-Mar or Oct", how: "Plant 3-bud setts in 90 cm furrows. Earth up at 90-120 days against lodging. Trash mulch saves moisture. Harvest at peak sugar (~12 months)." },
    tomato: { temp: "20-27°C", rain: "600-1250 mm", soil: "Well-drained loam rich in organic matter", ph: "6.0-7.0", season: "Year-round except peak summer/frost", how: "Transplant 25-30 day seedlings 60x45 cm. Stake plants. Avoid overhead watering (blight). Calcium prevents blossom-end rot. Pick at breaker stage." },
    watermelon: { temp: "24-30°C", rain: "400-600 mm", soil: "Sandy loam, warm and well-drained", ph: "6.0-7.0", season: "Summer (Jan-Mar sowing)", how: "Sow 3-4 seeds/pit at 2.5x1 m. Thin to 2 vines. Cut water during ripening for sweetness. Ripe when tendril near fruit dries; dull thump sound." },
    wheat: { temp: "14-25°C", rain: "450-650 mm", soil: "Well-drained loam or clay loam", ph: "6.0-7.5", season: "Rabi (Nov 1-20 optimal)", how: "Sow 100 kg/ha at 20-22 cm rows. First irrigation at 21 days (crown root) is most critical. Harvest at hard dough, ~12% moisture." },
};
